cargo-features = ["profile-overrides"]

[package]
name = "linear"
version = "0.1.0"
authors = ["monell <monell.zhong@gmail.com>"]
edition = "2018"


[profile.dev.overrides."*"]
opt-level = 3

[dependencies]
clap = "2.33.0"
num-traits = "0.2.8"
rayon = "1.2.0"
log = "0.4.8"
num-rational = "0.2.2"